version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    links:
      - php
  php:
    image: php:8.1.4-alpine
    links:
      - mysql
    command: php -S 0.0.0.0:8080 -t /var/www
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sait